### ISSUE TITLE
http://www.bootstrapmb.com/item/9920/preview 哥们谢了，已star

### ISSUE THREAD

**Issue by AmFe-GH** [AndersonHJB/bootstrapmb#4]

**Comment by AndersonHJB** [comment]
仓库里面也有：https://github.aiyc.top/bootstrapmb/muban/Smartdata/%E5%A4%A7%E6%B0%94%E5%A4%9A%E5%8A%9F%E8%83%BD%E4%BA%92%E8%81%94%E7%BD%91%E7%A7%91%E6%8A%80%E4%BC%81%E4%B8%9A%E7%BD%91%E7%AB%99%E6%A8%A1%E6%9D%BF-Smartdata.rar
