### ISSUE TITLE
大佬，麻烦您需要这两个模版，谢谢您啦，请您嚯咖啡～

### ISSUE THREAD

**Issue by bili-jing** [AndersonHJB/bootstrapmb#9]
http://www.bootstrapmb.com/item/9376/preview
http://www.bootstrapmb.com/item/8223/preview
麻烦大佬啦～

**Comment by AndersonHJB** [comment]
https://github.com/AndersonHJB/bootstrapmb/blob/main/muban/WritePress/WritePress.rar

**Comment by AndersonHJB** [comment]
https://github.com/AndersonHJB/bootstrapmb/blob/main/muban/Pressroom/Pressroom.rar

**Comment by AndersonHJB** [comment]
谢谢
